using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace OASTest.Models
{
    public class Values2
    {
        public string DataType { get; set; }
        public double Value { get; set; }
        public string ParameterSource { get; set; }
        public string OPCItem { get; set; }
        public string TagClientItem { get; set; }
        public bool Quality { get; set; }
        public bool IsTrendPoint { get; set; }
        public string Desc { get; set; }
        public string Units { get; set; }
        public int OPCUpdateRate { get; set; }
        public string OPCAccessPath { get; set; }
        public bool AlarmEnable { get; set; }
        public int AlarmPriority { get; set; }
        public string AlarmGroup { get; set; }
        public int AlarmDelayTime { get; set; }
        public int AlarmDeadband { get; set; }
        public bool ResetValue { get; set; }
        public string Calculation { get; set; }
        public bool TargetEnable { get; set; }
        public string TargetOPCItem { get; set; }
        public string TargetOPCAccessPath { get; set; }
        public int TargetOPCUpdateRate { get; set; }
        public double TimeStamp { get; set; }
        public bool EnableAlarmAck { get; set; }
        public string AlarmAckGroups { get; set; }
        public double TargetDeadband { get; set; }
        public bool LogAsEvent { get; set; }
        public bool TimeOnAndCountEnable { get; set; }
        public int TimeOnAndCountCurrentDayResetHour { get; set; }
        public int TimeOnAndCountCurrentDayResetMinute { get; set; }
        public int TimeOnAndCountPeriod1Minutes { get; set; }
        public int TimeOnAndCountPeriod2Minutes { get; set; }
        public bool SetAlarmText { get; set; }
        public string SetAlarmTextTag { get; set; }
        public bool ResetTimeOnAndCount { get; set; }
        public string ResetTimeOnAndCountTag { get; set; }
        public bool OPCEnumerated { get; set; }
        public string SourceValuesOnBadQuality { get; set; }
        public string DefaultValueType { get; set; }
        public int DefaultValue { get; set; }
        public string SetAlarmTextType { get; set; }
        public bool KeepOPCItemOnScan { get; set; }
        public bool EnableDeviceRead { get; set; }
        public string DeviceReadTag { get; set; }
        public string UDPClientItem { get; set; }
        public int TimeStampOffsetHours { get; set; }
        public bool TargetWriteContinuously { get; set; }
        public int TargetWriteContinuouslyFrequency { get; set; }
        public string TagForSourceOnBadQuality { get; set; }
        public bool OverrideOPCQualityOnBadQuality { get; set; }
        public int Gain { get; set; }
        public int Offset { get; set; }
        public bool DailyTimeRangeDisable { get; set; }
        public int DailyTimeRangeDisableStartHour { get; set; }
        public int DailyTimeRangeDisableStartMinute { get; set; }
        public int DailyTimeRangeDisableEndHour { get; set; }
        public int DailyTimeRangeDisableEndMinute { get; set; }
        public bool DateRangeDisable { get; set; }
        public int DateRangeDisableStart { get; set; }
        public int DateRangeDisableEnd { get; set; }
        public int HighRange { get; set; }
        public int LowRange { get; set; }
        public bool ReadOnlyValue { get; set; }
        public bool OPCEnableComm { get; set; }
        public string OPCEnableCommTag { get; set; }
        public bool AlarmEnableWithTag { get; set; }
        public string AlarmEnableTag { get; set; }
        public bool UseEnumeratedIndex { get; set; }
        public double OutOfRange { get; set; }
        public string ROCAlarmType { get; set; }
        public string DigitalAlarmTextAppendTrue { get; set; }
        public string DigitalAlarmTextAppendFalse { get; set; }
        public string Document { get; set; }
        public string SetAlarmTextCalculation { get; set; }
        public string DriverInterface { get; set; }
        public int DriverInterfacePollingRate { get; set; }
        public string ModbusMemoryType { get; set; }
        public int ModbusDeviceAddress { get; set; }
        public string ModbusDataType { get; set; }
        public int ModbusAddress { get; set; }
        public int ModbusBitPosition { get; set; }
        public int ModbusNumberOfWordsForString { get; set; }
        public int ModbusMaxWordsPerPacket { get; set; }
        public bool ModbusWordSwap { get; set; }
        public bool ModbusByteSwap { get; set; }
        public bool ModbusZeroBasedAddressing { get; set; }
        public bool DriverInterfaceKeepItemOnScan { get; set; }
        public bool DriverInterfaceEnableDeviceRead { get; set; }
        public string DriverInterfaceDeviceReadTag { get; set; }
        public bool DriverInterfaceEnableComm { get; set; }
        public string DriverInterfaceEnableCommTag { get; set; }
        public string ABLogixDataType { get; set; }
        public string ABAddress { get; set; }
        public string SiemensAddress { get; set; }
        public string TargetDestinationType { get; set; }
        public string TargetTag { get; set; }
        public string SiemensDataType { get; set; }
        public string MQTTTopic { get; set; }
        public string MQTTQoS { get; set; }
        public int MQTTTopicTimeout { get; set; }
        public bool MQTTIncludeTimeStamp { get; set; }
        public bool MQTTIncludeQuality { get; set; }
        public int SiemensStringLength { get; set; }
        public string TargetAzureIoTDriverInterface { get; set; }
        public string AWSIoTGatewayTopic { get; set; }
        public int AWSIoTGatewayTopicTimeout { get; set; }
        public bool AWSIoTGatewayIncludeTimeStamp { get; set; }
        public bool AWSIoTGatewayIncludeQuality { get; set; }
        public int CANBusBlockNumber { get; set; }
        public int CANBusIndex { get; set; }
    }

    public class HighHighAlarmLimit
    {
        public string DataType { get; set; }
        public int Value { get; set; }
        public string ParameterSource { get; set; }
        public string OPCItem { get; set; }
        public string TagClientItem { get; set; }
        public bool Quality { get; set; }
        public bool IsTrendPoint { get; set; }
        public string Desc { get; set; }
        public string Units { get; set; }
        public int OPCUpdateRate { get; set; }
        public string OPCAccessPath { get; set; }
        public bool AlarmEnable { get; set; }
        public int AlarmPriority { get; set; }
        public string AlarmGroup { get; set; }
        public int AlarmDelayTime { get; set; }
        public int AlarmDeadband { get; set; }
        public bool ResetValue { get; set; }
        public string Calculation { get; set; }
        public bool TargetEnable { get; set; }
        public string TargetOPCItem { get; set; }
        public string TargetOPCAccessPath { get; set; }
        public int TargetOPCUpdateRate { get; set; }
        public double TimeStamp { get; set; }
        public bool EnableAlarmAck { get; set; }
        public string AlarmAckGroups { get; set; }
        public double TargetDeadband { get; set; }
        public bool LogAsEvent { get; set; }
        public bool TimeOnAndCountEnable { get; set; }
        public int TimeOnAndCountCurrentDayResetHour { get; set; }
        public int TimeOnAndCountCurrentDayResetMinute { get; set; }
        public int TimeOnAndCountPeriod1Minutes { get; set; }
        public int TimeOnAndCountPeriod2Minutes { get; set; }
        public bool SetAlarmText { get; set; }
        public string SetAlarmTextTag { get; set; }
        public bool ResetTimeOnAndCount { get; set; }
        public string ResetTimeOnAndCountTag { get; set; }
        public bool OPCEnumerated { get; set; }
        public string SourceValuesOnBadQuality { get; set; }
        public string DefaultValueType { get; set; }
        public int DefaultValue { get; set; }
        public string SetAlarmTextType { get; set; }
        public bool KeepOPCItemOnScan { get; set; }
        public bool EnableDeviceRead { get; set; }
        public string DeviceReadTag { get; set; }
        public string UDPClientItem { get; set; }
        public int TimeStampOffsetHours { get; set; }
        public bool TargetWriteContinuously { get; set; }
        public int TargetWriteContinuouslyFrequency { get; set; }
        public string TagForSourceOnBadQuality { get; set; }
        public bool OverrideOPCQualityOnBadQuality { get; set; }
        public int Gain { get; set; }
        public int Offset { get; set; }
        public bool DailyTimeRangeDisable { get; set; }
        public int DailyTimeRangeDisableStartHour { get; set; }
        public int DailyTimeRangeDisableStartMinute { get; set; }
        public int DailyTimeRangeDisableEndHour { get; set; }
        public int DailyTimeRangeDisableEndMinute { get; set; }
        public bool DateRangeDisable { get; set; }
        public int DateRangeDisableStart { get; set; }
        public int DateRangeDisableEnd { get; set; }
        public int HighRange { get; set; }
        public int LowRange { get; set; }
        public bool ReadOnlyValue { get; set; }
        public bool OPCEnableComm { get; set; }
        public string OPCEnableCommTag { get; set; }
        public bool AlarmEnableWithTag { get; set; }
        public string AlarmEnableTag { get; set; }
        public bool UseEnumeratedIndex { get; set; }
        public double OutOfRange { get; set; }
        public string ROCAlarmType { get; set; }
        public string DigitalAlarmTextAppendTrue { get; set; }
        public string DigitalAlarmTextAppendFalse { get; set; }
        public string Document { get; set; }
        public string SetAlarmTextCalculation { get; set; }
        public string DriverInterface { get; set; }
        public int DriverInterfacePollingRate { get; set; }
        public string ModbusMemoryType { get; set; }
        public int ModbusDeviceAddress { get; set; }
        public string ModbusDataType { get; set; }
        public int ModbusAddress { get; set; }
        public int ModbusBitPosition { get; set; }
        public int ModbusNumberOfWordsForString { get; set; }
        public int ModbusMaxWordsPerPacket { get; set; }
        public bool ModbusWordSwap { get; set; }
        public bool ModbusByteSwap { get; set; }
        public bool ModbusZeroBasedAddressing { get; set; }
        public bool DriverInterfaceKeepItemOnScan { get; set; }
        public bool DriverInterfaceEnableDeviceRead { get; set; }
        public string DriverInterfaceDeviceReadTag { get; set; }
        public bool DriverInterfaceEnableComm { get; set; }
        public string DriverInterfaceEnableCommTag { get; set; }
        public string ABLogixDataType { get; set; }
        public string ABAddress { get; set; }
        public string SiemensAddress { get; set; }
        public string TargetDestinationType { get; set; }
        public string TargetTag { get; set; }
        public string SiemensDataType { get; set; }
        public string MQTTTopic { get; set; }
        public string MQTTQoS { get; set; }
        public int MQTTTopicTimeout { get; set; }
        public bool MQTTIncludeTimeStamp { get; set; }
        public bool MQTTIncludeQuality { get; set; }
        public int SiemensStringLength { get; set; }
        public string TargetAzureIoTDriverInterface { get; set; }
        public string AWSIoTGatewayTopic { get; set; }
        public int AWSIoTGatewayTopicTimeout { get; set; }
        public bool AWSIoTGatewayIncludeTimeStamp { get; set; }
        public bool AWSIoTGatewayIncludeQuality { get; set; }
        public int CANBusBlockNumber { get; set; }
        public int CANBusIndex { get; set; }
    }

    public class HighAlarmLimit
    {
        public string DataType { get; set; }
        public int Value { get; set; }
        public string ParameterSource { get; set; }
        public string OPCItem { get; set; }
        public string TagClientItem { get; set; }
        public bool Quality { get; set; }
        public bool IsTrendPoint { get; set; }
        public string Desc { get; set; }
        public string Units { get; set; }
        public int OPCUpdateRate { get; set; }
        public string OPCAccessPath { get; set; }
        public bool AlarmEnable { get; set; }
        public int AlarmPriority { get; set; }
        public string AlarmGroup { get; set; }
        public int AlarmDelayTime { get; set; }
        public int AlarmDeadband { get; set; }
        public bool ResetValue { get; set; }
        public string Calculation { get; set; }
        public bool TargetEnable { get; set; }
        public string TargetOPCItem { get; set; }
        public string TargetOPCAccessPath { get; set; }
        public int TargetOPCUpdateRate { get; set; }
        public double TimeStamp { get; set; }
        public bool EnableAlarmAck { get; set; }
        public string AlarmAckGroups { get; set; }
        public double TargetDeadband { get; set; }
        public bool LogAsEvent { get; set; }
        public bool TimeOnAndCountEnable { get; set; }
        public int TimeOnAndCountCurrentDayResetHour { get; set; }
        public int TimeOnAndCountCurrentDayResetMinute { get; set; }
        public int TimeOnAndCountPeriod1Minutes { get; set; }
        public int TimeOnAndCountPeriod2Minutes { get; set; }
        public bool SetAlarmText { get; set; }
        public string SetAlarmTextTag { get; set; }
        public bool ResetTimeOnAndCount { get; set; }
        public string ResetTimeOnAndCountTag { get; set; }
        public bool OPCEnumerated { get; set; }
        public string SourceValuesOnBadQuality { get; set; }
        public string DefaultValueType { get; set; }
        public int DefaultValue { get; set; }
        public string SetAlarmTextType { get; set; }
        public bool KeepOPCItemOnScan { get; set; }
        public bool EnableDeviceRead { get; set; }
        public string DeviceReadTag { get; set; }
        public string UDPClientItem { get; set; }
        public int TimeStampOffsetHours { get; set; }
        public bool TargetWriteContinuously { get; set; }
        public int TargetWriteContinuouslyFrequency { get; set; }
        public string TagForSourceOnBadQuality { get; set; }
        public bool OverrideOPCQualityOnBadQuality { get; set; }
        public int Gain { get; set; }
        public int Offset { get; set; }
        public bool DailyTimeRangeDisable { get; set; }
        public int DailyTimeRangeDisableStartHour { get; set; }
        public int DailyTimeRangeDisableStartMinute { get; set; }
        public int DailyTimeRangeDisableEndHour { get; set; }
        public int DailyTimeRangeDisableEndMinute { get; set; }
        public bool DateRangeDisable { get; set; }
        public int DateRangeDisableStart { get; set; }
        public int DateRangeDisableEnd { get; set; }
        public int HighRange { get; set; }
        public int LowRange { get; set; }
        public bool ReadOnlyValue { get; set; }
        public bool OPCEnableComm { get; set; }
        public string OPCEnableCommTag { get; set; }
        public bool AlarmEnableWithTag { get; set; }
        public string AlarmEnableTag { get; set; }
        public bool UseEnumeratedIndex { get; set; }
        public double OutOfRange { get; set; }
        public string ROCAlarmType { get; set; }
        public string DigitalAlarmTextAppendTrue { get; set; }
        public string DigitalAlarmTextAppendFalse { get; set; }
        public string Document { get; set; }
        public string SetAlarmTextCalculation { get; set; }
        public string DriverInterface { get; set; }
        public int DriverInterfacePollingRate { get; set; }
        public string ModbusMemoryType { get; set; }
        public int ModbusDeviceAddress { get; set; }
        public string ModbusDataType { get; set; }
        public int ModbusAddress { get; set; }
        public int ModbusBitPosition { get; set; }
        public int ModbusNumberOfWordsForString { get; set; }
        public int ModbusMaxWordsPerPacket { get; set; }
        public bool ModbusWordSwap { get; set; }
        public bool ModbusByteSwap { get; set; }
        public bool ModbusZeroBasedAddressing { get; set; }
        public bool DriverInterfaceKeepItemOnScan { get; set; }
        public bool DriverInterfaceEnableDeviceRead { get; set; }
        public string DriverInterfaceDeviceReadTag { get; set; }
        public bool DriverInterfaceEnableComm { get; set; }
        public string DriverInterfaceEnableCommTag { get; set; }
        public string ABLogixDataType { get; set; }
        public string ABAddress { get; set; }
        public string SiemensAddress { get; set; }
        public string TargetDestinationType { get; set; }
        public string TargetTag { get; set; }
        public string SiemensDataType { get; set; }
        public string MQTTTopic { get; set; }
        public string MQTTQoS { get; set; }
        public int MQTTTopicTimeout { get; set; }
        public bool MQTTIncludeTimeStamp { get; set; }
        public bool MQTTIncludeQuality { get; set; }
        public int SiemensStringLength { get; set; }
        public string TargetAzureIoTDriverInterface { get; set; }
        public string AWSIoTGatewayTopic { get; set; }
        public int AWSIoTGatewayTopicTimeout { get; set; }
        public bool AWSIoTGatewayIncludeTimeStamp { get; set; }
        public bool AWSIoTGatewayIncludeQuality { get; set; }
        public int CANBusBlockNumber { get; set; }
        public int CANBusIndex { get; set; }
    }

    public class LowAlarmLimit
    {
        public string DataType { get; set; }
        public int Value { get; set; }
        public string ParameterSource { get; set; }
        public string OPCItem { get; set; }
        public string TagClientItem { get; set; }
        public bool Quality { get; set; }
        public bool IsTrendPoint { get; set; }
        public string Desc { get; set; }
        public string Units { get; set; }
        public int OPCUpdateRate { get; set; }
        public string OPCAccessPath { get; set; }
        public bool AlarmEnable { get; set; }
        public int AlarmPriority { get; set; }
        public string AlarmGroup { get; set; }
        public int AlarmDelayTime { get; set; }
        public int AlarmDeadband { get; set; }
        public bool ResetValue { get; set; }
        public string Calculation { get; set; }
        public bool TargetEnable { get; set; }
        public string TargetOPCItem { get; set; }
        public string TargetOPCAccessPath { get; set; }
        public int TargetOPCUpdateRate { get; set; }
        public double TimeStamp { get; set; }
        public bool EnableAlarmAck { get; set; }
        public string AlarmAckGroups { get; set; }
        public double TargetDeadband { get; set; }
        public bool LogAsEvent { get; set; }
        public bool TimeOnAndCountEnable { get; set; }
        public int TimeOnAndCountCurrentDayResetHour { get; set; }
        public int TimeOnAndCountCurrentDayResetMinute { get; set; }
        public int TimeOnAndCountPeriod1Minutes { get; set; }
        public int TimeOnAndCountPeriod2Minutes { get; set; }
        public bool SetAlarmText { get; set; }
        public string SetAlarmTextTag { get; set; }
        public bool ResetTimeOnAndCount { get; set; }
        public string ResetTimeOnAndCountTag { get; set; }
        public bool OPCEnumerated { get; set; }
        public string SourceValuesOnBadQuality { get; set; }
        public string DefaultValueType { get; set; }
        public int DefaultValue { get; set; }
        public string SetAlarmTextType { get; set; }
        public bool KeepOPCItemOnScan { get; set; }
        public bool EnableDeviceRead { get; set; }
        public string DeviceReadTag { get; set; }
        public string UDPClientItem { get; set; }
        public int TimeStampOffsetHours { get; set; }
        public bool TargetWriteContinuously { get; set; }
        public int TargetWriteContinuouslyFrequency { get; set; }
        public string TagForSourceOnBadQuality { get; set; }
        public bool OverrideOPCQualityOnBadQuality { get; set; }
        public int Gain { get; set; }
        public int Offset { get; set; }
        public bool DailyTimeRangeDisable { get; set; }
        public int DailyTimeRangeDisableStartHour { get; set; }
        public int DailyTimeRangeDisableStartMinute { get; set; }
        public int DailyTimeRangeDisableEndHour { get; set; }
        public int DailyTimeRangeDisableEndMinute { get; set; }
        public bool DateRangeDisable { get; set; }
        public int DateRangeDisableStart { get; set; }
        public int DateRangeDisableEnd { get; set; }
        public int HighRange { get; set; }
        public int LowRange { get; set; }
        public bool ReadOnlyValue { get; set; }
        public bool OPCEnableComm { get; set; }
        public string OPCEnableCommTag { get; set; }
        public bool AlarmEnableWithTag { get; set; }
        public string AlarmEnableTag { get; set; }
        public bool UseEnumeratedIndex { get; set; }
        public double OutOfRange { get; set; }
        public string ROCAlarmType { get; set; }
        public string DigitalAlarmTextAppendTrue { get; set; }
        public string DigitalAlarmTextAppendFalse { get; set; }
        public string Document { get; set; }
        public string SetAlarmTextCalculation { get; set; }
        public string DriverInterface { get; set; }
        public int DriverInterfacePollingRate { get; set; }
        public string ModbusMemoryType { get; set; }
        public int ModbusDeviceAddress { get; set; }
        public string ModbusDataType { get; set; }
        public int ModbusAddress { get; set; }
        public int ModbusBitPosition { get; set; }
        public int ModbusNumberOfWordsForString { get; set; }
        public int ModbusMaxWordsPerPacket { get; set; }
        public bool ModbusWordSwap { get; set; }
        public bool ModbusByteSwap { get; set; }
        public bool ModbusZeroBasedAddressing { get; set; }
        public bool DriverInterfaceKeepItemOnScan { get; set; }
        public bool DriverInterfaceEnableDeviceRead { get; set; }
        public string DriverInterfaceDeviceReadTag { get; set; }
        public bool DriverInterfaceEnableComm { get; set; }
        public string DriverInterfaceEnableCommTag { get; set; }
        public string ABLogixDataType { get; set; }
        public string ABAddress { get; set; }
        public string SiemensAddress { get; set; }
        public string TargetDestinationType { get; set; }
        public string TargetTag { get; set; }
        public string SiemensDataType { get; set; }
        public string MQTTTopic { get; set; }
        public string MQTTQoS { get; set; }
        public int MQTTTopicTimeout { get; set; }
        public bool MQTTIncludeTimeStamp { get; set; }
        public bool MQTTIncludeQuality { get; set; }
        public int SiemensStringLength { get; set; }
        public string TargetAzureIoTDriverInterface { get; set; }
        public string AWSIoTGatewayTopic { get; set; }
        public int AWSIoTGatewayTopicTimeout { get; set; }
        public bool AWSIoTGatewayIncludeTimeStamp { get; set; }
        public bool AWSIoTGatewayIncludeQuality { get; set; }
        public int CANBusBlockNumber { get; set; }
        public int CANBusIndex { get; set; }
    }

    public class LowLowAlarmLimit
    {
        public string DataType { get; set; }
        public int Value { get; set; }
        public string ParameterSource { get; set; }
        public string OPCItem { get; set; }
        public string TagClientItem { get; set; }
        public bool Quality { get; set; }
        public bool IsTrendPoint { get; set; }
        public string Desc { get; set; }
        public string Units { get; set; }
        public int OPCUpdateRate { get; set; }
        public string OPCAccessPath { get; set; }
        public bool AlarmEnable { get; set; }
        public int AlarmPriority { get; set; }
        public string AlarmGroup { get; set; }
        public int AlarmDelayTime { get; set; }
        public int AlarmDeadband { get; set; }
        public bool ResetValue { get; set; }
        public string Calculation { get; set; }
        public bool TargetEnable { get; set; }
        public string TargetOPCItem { get; set; }
        public string TargetOPCAccessPath { get; set; }
        public int TargetOPCUpdateRate { get; set; }
        public double TimeStamp { get; set; }
        public bool EnableAlarmAck { get; set; }
        public string AlarmAckGroups { get; set; }
        public double TargetDeadband { get; set; }
        public bool LogAsEvent { get; set; }
        public bool TimeOnAndCountEnable { get; set; }
        public int TimeOnAndCountCurrentDayResetHour { get; set; }
        public int TimeOnAndCountCurrentDayResetMinute { get; set; }
        public int TimeOnAndCountPeriod1Minutes { get; set; }
        public int TimeOnAndCountPeriod2Minutes { get; set; }
        public bool SetAlarmText { get; set; }
        public string SetAlarmTextTag { get; set; }
        public bool ResetTimeOnAndCount { get; set; }
        public string ResetTimeOnAndCountTag { get; set; }
        public bool OPCEnumerated { get; set; }
        public string SourceValuesOnBadQuality { get; set; }
        public string DefaultValueType { get; set; }
        public int DefaultValue { get; set; }
        public string SetAlarmTextType { get; set; }
        public bool KeepOPCItemOnScan { get; set; }
        public bool EnableDeviceRead { get; set; }
        public string DeviceReadTag { get; set; }
        public string UDPClientItem { get; set; }
        public int TimeStampOffsetHours { get; set; }
        public bool TargetWriteContinuously { get; set; }
        public int TargetWriteContinuouslyFrequency { get; set; }
        public string TagForSourceOnBadQuality { get; set; }
        public bool OverrideOPCQualityOnBadQuality { get; set; }
        public int Gain { get; set; }
        public int Offset { get; set; }
        public bool DailyTimeRangeDisable { get; set; }
        public int DailyTimeRangeDisableStartHour { get; set; }
        public int DailyTimeRangeDisableStartMinute { get; set; }
        public int DailyTimeRangeDisableEndHour { get; set; }
        public int DailyTimeRangeDisableEndMinute { get; set; }
        public bool DateRangeDisable { get; set; }
        public int DateRangeDisableStart { get; set; }
        public int DateRangeDisableEnd { get; set; }
        public int HighRange { get; set; }
        public int LowRange { get; set; }
        public bool ReadOnlyValue { get; set; }
        public bool OPCEnableComm { get; set; }
        public string OPCEnableCommTag { get; set; }
        public bool AlarmEnableWithTag { get; set; }
        public string AlarmEnableTag { get; set; }
        public bool UseEnumeratedIndex { get; set; }
        public double OutOfRange { get; set; }
        public string ROCAlarmType { get; set; }
        public string DigitalAlarmTextAppendTrue { get; set; }
        public string DigitalAlarmTextAppendFalse { get; set; }
        public string Document { get; set; }
        public string SetAlarmTextCalculation { get; set; }
        public string DriverInterface { get; set; }
        public int DriverInterfacePollingRate { get; set; }
        public string ModbusMemoryType { get; set; }
        public int ModbusDeviceAddress { get; set; }
        public string ModbusDataType { get; set; }
        public int ModbusAddress { get; set; }
        public int ModbusBitPosition { get; set; }
        public int ModbusNumberOfWordsForString { get; set; }
        public int ModbusMaxWordsPerPacket { get; set; }
        public bool ModbusWordSwap { get; set; }
        public bool ModbusByteSwap { get; set; }
        public bool ModbusZeroBasedAddressing { get; set; }
        public bool DriverInterfaceKeepItemOnScan { get; set; }
        public bool DriverInterfaceEnableDeviceRead { get; set; }
        public string DriverInterfaceDeviceReadTag { get; set; }
        public bool DriverInterfaceEnableComm { get; set; }
        public string DriverInterfaceEnableCommTag { get; set; }
        public string ABLogixDataType { get; set; }
        public string ABAddress { get; set; }
        public string SiemensAddress { get; set; }
        public string TargetDestinationType { get; set; }
        public string TargetTag { get; set; }
        public string SiemensDataType { get; set; }
        public string MQTTTopic { get; set; }
        public string MQTTQoS { get; set; }
        public int MQTTTopicTimeout { get; set; }
        public bool MQTTIncludeTimeStamp { get; set; }
        public bool MQTTIncludeQuality { get; set; }
        public int SiemensStringLength { get; set; }
        public string TargetAzureIoTDriverInterface { get; set; }
        public string AWSIoTGatewayTopic { get; set; }
        public int AWSIoTGatewayTopicTimeout { get; set; }
        public bool AWSIoTGatewayIncludeTimeStamp { get; set; }
        public bool AWSIoTGatewayIncludeQuality { get; set; }
        public int CANBusBlockNumber { get; set; }
        public int CANBusIndex { get; set; }
    }

    public class DigitalAlarmLimit
    {
        public string DataType { get; set; }
        public bool Value { get; set; }
        public string ParameterSource { get; set; }
        public string OPCItem { get; set; }
        public string TagClientItem { get; set; }
        public bool Quality { get; set; }
        public bool IsTrendPoint { get; set; }
        public string Desc { get; set; }
        public string Units { get; set; }
        public int OPCUpdateRate { get; set; }
        public string OPCAccessPath { get; set; }
        public bool AlarmEnable { get; set; }
        public int AlarmPriority { get; set; }
        public string AlarmGroup { get; set; }
        public int AlarmDelayTime { get; set; }
        public int AlarmDeadband { get; set; }
        public bool ResetValue { get; set; }
        public string Calculation { get; set; }
        public bool TargetEnable { get; set; }
        public string TargetOPCItem { get; set; }
        public string TargetOPCAccessPath { get; set; }
        public int TargetOPCUpdateRate { get; set; }
        public double TimeStamp { get; set; }
        public bool EnableAlarmAck { get; set; }
        public string AlarmAckGroups { get; set; }
        public double TargetDeadband { get; set; }
        public bool LogAsEvent { get; set; }
        public bool TimeOnAndCountEnable { get; set; }
        public int TimeOnAndCountCurrentDayResetHour { get; set; }
        public int TimeOnAndCountCurrentDayResetMinute { get; set; }
        public int TimeOnAndCountPeriod1Minutes { get; set; }
        public int TimeOnAndCountPeriod2Minutes { get; set; }
        public bool SetAlarmText { get; set; }
        public string SetAlarmTextTag { get; set; }
        public bool ResetTimeOnAndCount { get; set; }
        public string ResetTimeOnAndCountTag { get; set; }
        public bool OPCEnumerated { get; set; }
        public string SourceValuesOnBadQuality { get; set; }
        public string DefaultValueType { get; set; }
        public int DefaultValue { get; set; }
        public string SetAlarmTextType { get; set; }
        public bool KeepOPCItemOnScan { get; set; }
        public bool EnableDeviceRead { get; set; }
        public string DeviceReadTag { get; set; }
        public string UDPClientItem { get; set; }
        public int TimeStampOffsetHours { get; set; }
        public bool TargetWriteContinuously { get; set; }
        public int TargetWriteContinuouslyFrequency { get; set; }
        public string TagForSourceOnBadQuality { get; set; }
        public bool OverrideOPCQualityOnBadQuality { get; set; }
        public int Gain { get; set; }
        public int Offset { get; set; }
        public bool DailyTimeRangeDisable { get; set; }
        public int DailyTimeRangeDisableStartHour { get; set; }
        public int DailyTimeRangeDisableStartMinute { get; set; }
        public int DailyTimeRangeDisableEndHour { get; set; }
        public int DailyTimeRangeDisableEndMinute { get; set; }
        public bool DateRangeDisable { get; set; }
        public int DateRangeDisableStart { get; set; }
        public int DateRangeDisableEnd { get; set; }
        public int HighRange { get; set; }
        public int LowRange { get; set; }
        public bool ReadOnlyValue { get; set; }
        public bool OPCEnableComm { get; set; }
        public string OPCEnableCommTag { get; set; }
        public bool AlarmEnableWithTag { get; set; }
        public string AlarmEnableTag { get; set; }
        public bool UseEnumeratedIndex { get; set; }
        public string ROCAlarmType { get; set; }
        public string DigitalAlarmTextAppendTrue { get; set; }
        public string DigitalAlarmTextAppendFalse { get; set; }
        public string Document { get; set; }
        public string SetAlarmTextCalculation { get; set; }
        public string DriverInterface { get; set; }
        public int DriverInterfacePollingRate { get; set; }
        public string ModbusMemoryType { get; set; }
        public int ModbusDeviceAddress { get; set; }
        public string ModbusDataType { get; set; }
        public int ModbusAddress { get; set; }
        public int ModbusBitPosition { get; set; }
        public int ModbusNumberOfWordsForString { get; set; }
        public int ModbusMaxWordsPerPacket { get; set; }
        public bool ModbusWordSwap { get; set; }
        public bool ModbusByteSwap { get; set; }
        public bool ModbusZeroBasedAddressing { get; set; }
        public bool DriverInterfaceKeepItemOnScan { get; set; }
        public bool DriverInterfaceEnableDeviceRead { get; set; }
        public string DriverInterfaceDeviceReadTag { get; set; }
        public bool DriverInterfaceEnableComm { get; set; }
        public string DriverInterfaceEnableCommTag { get; set; }
        public string ABLogixDataType { get; set; }
        public string ABAddress { get; set; }
        public string SiemensAddress { get; set; }
        public string TargetDestinationType { get; set; }
        public string TargetTag { get; set; }
        public string SiemensDataType { get; set; }
        public string MQTTTopic { get; set; }
        public string MQTTQoS { get; set; }
        public int MQTTTopicTimeout { get; set; }
        public bool MQTTIncludeTimeStamp { get; set; }
        public bool MQTTIncludeQuality { get; set; }
        public int SiemensStringLength { get; set; }
        public string TargetAzureIoTDriverInterface { get; set; }
        public string AWSIoTGatewayTopic { get; set; }
        public int AWSIoTGatewayTopicTimeout { get; set; }
        public bool AWSIoTGatewayIncludeTimeStamp { get; set; }
        public bool AWSIoTGatewayIncludeQuality { get; set; }
        public int CANBusBlockNumber { get; set; }
        public int CANBusIndex { get; set; }
    }

    public class ROCAlarmLimit
    {
        public string DataType { get; set; }
        public int Value { get; set; }
        public string ParameterSource { get; set; }
        public string OPCItem { get; set; }
        public string TagClientItem { get; set; }
        public bool Quality { get; set; }
        public bool IsTrendPoint { get; set; }
        public string Desc { get; set; }
        public string Units { get; set; }
        public int OPCUpdateRate { get; set; }
        public string OPCAccessPath { get; set; }
        public bool AlarmEnable { get; set; }
        public int AlarmPriority { get; set; }
        public string AlarmGroup { get; set; }
        public int AlarmDelayTime { get; set; }
        public int AlarmDeadband { get; set; }
        public bool ResetValue { get; set; }
        public string Calculation { get; set; }
        public bool TargetEnable { get; set; }
        public string TargetOPCItem { get; set; }
        public string TargetOPCAccessPath { get; set; }
        public int TargetOPCUpdateRate { get; set; }
        public double TimeStamp { get; set; }
        public bool EnableAlarmAck { get; set; }
        public string AlarmAckGroups { get; set; }
        public double TargetDeadband { get; set; }
        public bool LogAsEvent { get; set; }
        public bool TimeOnAndCountEnable { get; set; }
        public int TimeOnAndCountCurrentDayResetHour { get; set; }
        public int TimeOnAndCountCurrentDayResetMinute { get; set; }
        public int TimeOnAndCountPeriod1Minutes { get; set; }
        public int TimeOnAndCountPeriod2Minutes { get; set; }
        public bool SetAlarmText { get; set; }
        public string SetAlarmTextTag { get; set; }
        public bool ResetTimeOnAndCount { get; set; }
        public string ResetTimeOnAndCountTag { get; set; }
        public bool OPCEnumerated { get; set; }
        public string SourceValuesOnBadQuality { get; set; }
        public string DefaultValueType { get; set; }
        public int DefaultValue { get; set; }
        public string SetAlarmTextType { get; set; }
        public bool KeepOPCItemOnScan { get; set; }
        public bool EnableDeviceRead { get; set; }
        public string DeviceReadTag { get; set; }
        public string UDPClientItem { get; set; }
        public int TimeStampOffsetHours { get; set; }
        public bool TargetWriteContinuously { get; set; }
        public int TargetWriteContinuouslyFrequency { get; set; }
        public string TagForSourceOnBadQuality { get; set; }
        public bool OverrideOPCQualityOnBadQuality { get; set; }
        public int Gain { get; set; }
        public int Offset { get; set; }
        public bool DailyTimeRangeDisable { get; set; }
        public int DailyTimeRangeDisableStartHour { get; set; }
        public int DailyTimeRangeDisableStartMinute { get; set; }
        public int DailyTimeRangeDisableEndHour { get; set; }
        public int DailyTimeRangeDisableEndMinute { get; set; }
        public bool DateRangeDisable { get; set; }
        public int DateRangeDisableStart { get; set; }
        public int DateRangeDisableEnd { get; set; }
        public int HighRange { get; set; }
        public int LowRange { get; set; }
        public bool ReadOnlyValue { get; set; }
        public bool OPCEnableComm { get; set; }
        public string OPCEnableCommTag { get; set; }
        public bool AlarmEnableWithTag { get; set; }
        public string AlarmEnableTag { get; set; }
        public bool UseEnumeratedIndex { get; set; }
        public double OutOfRange { get; set; }
        public string ROCAlarmType { get; set; }
        public string DigitalAlarmTextAppendTrue { get; set; }
        public string DigitalAlarmTextAppendFalse { get; set; }
        public string Document { get; set; }
        public string SetAlarmTextCalculation { get; set; }
        public string DriverInterface { get; set; }
        public int DriverInterfacePollingRate { get; set; }
        public string ModbusMemoryType { get; set; }
        public int ModbusDeviceAddress { get; set; }
        public string ModbusDataType { get; set; }
        public int ModbusAddress { get; set; }
        public int ModbusBitPosition { get; set; }
        public int ModbusNumberOfWordsForString { get; set; }
        public int ModbusMaxWordsPerPacket { get; set; }
        public bool ModbusWordSwap { get; set; }
        public bool ModbusByteSwap { get; set; }
        public bool ModbusZeroBasedAddressing { get; set; }
        public bool DriverInterfaceKeepItemOnScan { get; set; }
        public bool DriverInterfaceEnableDeviceRead { get; set; }
        public string DriverInterfaceDeviceReadTag { get; set; }
        public bool DriverInterfaceEnableComm { get; set; }
        public string DriverInterfaceEnableCommTag { get; set; }
        public string ABLogixDataType { get; set; }
        public string ABAddress { get; set; }
        public string SiemensAddress { get; set; }
        public string TargetDestinationType { get; set; }
        public string TargetTag { get; set; }
        public string SiemensDataType { get; set; }
        public string MQTTTopic { get; set; }
        public string MQTTQoS { get; set; }
        public int MQTTTopicTimeout { get; set; }
        public bool MQTTIncludeTimeStamp { get; set; }
        public bool MQTTIncludeQuality { get; set; }
        public int SiemensStringLength { get; set; }
        public string TargetAzureIoTDriverInterface { get; set; }
        public string AWSIoTGatewayTopic { get; set; }
        public int AWSIoTGatewayTopicTimeout { get; set; }
        public bool AWSIoTGatewayIncludeTimeStamp { get; set; }
        public bool AWSIoTGatewayIncludeQuality { get; set; }
        public int CANBusBlockNumber { get; set; }
        public int CANBusIndex { get; set; }
    }

    public class Parameters2
    {
        public Values2 Value { get; set; }
        //public HighHighAlarmLimit HighHighAlarmLimit { get; set; }
        //public HighAlarmLimit HighAlarmLimit { get; set; }
        //public LowAlarmLimit LowAlarmLimit { get; set; }
        //public LowLowAlarmLimit LowLowAlarmLimit { get; set; }
        //public DigitalAlarmLimit DigitalAlarmLimit { get; set; }
        //public ROCAlarmLimit ROCAlarmLimit { get; set; }
    }

    public class RootObject
    {
        public string path { get; set; }
        public string value { get; set; }
        public bool quality { get; set; }
        public string type { get; set; }
        public double timestamp { get; set; }
        //public List<Parameters> parameters { get; set; }
    }

    public class TagContainer
    {
        public RootObject rootObject { get; set; }
    }

    public class MultipleTags
    {
        public bool success { get; set; }
        public string Message { get; set; }
        public List<TagContainer> Tags { get; set; }
    }
}